

### ─────────────────────────────────────────
### POST
### ─────────────────────────────────────────

### Create avg health readings for driver (system authorization)

POST http://localhost:3000/api/users/17/avg-health-readings
Content-Type: application/json
X-Api-Key: 1234782181veryyyyloonngggrandomkey

{
    "avgHeartRate": 60,
    "avgTemp": 36,
    "avgSpo2": 50,
    "tripId": 26
}


### Create avg health readings for driver (other than system authorization) - should fail

POST http://localhost:3000/api/users/:userId/avg-health-readings/6
Content-Type: application/json
Authorization: Bearer DRIVER_TOKEN

{
    "heartRate": 60,
    "temp": 36,
    "spo2": 50

}



