POST http://localhost:3000/api/emergency-service-request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3NjUzNzU1LCJleHAiOjE3Nzc3NDAxNTV9.c73B-EOWx0roPbkqm9Y6S6EUqVwo9J2SrA3Mi8SRSvY

{ 
    "phone":"01100040",
    "hospitalAssigned":"China Hospital",
    "alertId": 2
    
}
#########
GET http://localhost:3000/api/emergency-service-request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3Mzk2ODkwLCJleHAiOjE3Nzc0ODMyOTB9.yYDcNkGg5f9W7MNIV7WPparZXZnsENbuV86l4C8Qszo

{ 
   
}
#######
PATCH http://localhost:3000/api/emergency-service-request/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3Mzk2ODkwLCJleHAiOjE3Nzc0ODMyOTB9.yYDcNkGg5f9W7MNIV7WPparZXZnsENbuV86l4C8Qszo

{ 
    "status": "COMPLETED",
    "completionTime": "2026-04-28T17:47:15.747Z"
    
}
#######
DELETE http://localhost:3000/api/emergency-service-request/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3Mzk2ODkwLCJleHAiOjE3Nzc0ODMyOTB9.yYDcNkGg5f9W7MNIV7WPparZXZnsENbuV86l4C8Qszo

{ 

}