POST http://localhost:3000/api/emergency-service-request/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc4MTgzODAwNSwiZXhwIjoxNzgxOTI0NDA1fQ.f0XVfbyzz_2cCgtuSbgtwZ_X7wuXozH6mWTm2FFD6NI

{ 
    "phone":"01100040",
    "hospitalAssigned":"China Hospital",
    "alertId": 116
    
}
#########
GET http://localhost:3000/api/emergency-service-request?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc4MTgzODAwNSwiZXhwIjoxNzgxOTI0NDA1fQ.f0XVfbyzz_2cCgtuSbgtwZ_X7wuXozH6mWTm2FFD6NI


#########
GET http://localhost:3000/api/towing-requests/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc4MTgwNzg3NywiZXhwIjoxNzgxODk0Mjc3fQ.gd9YWuKMTwiyAxEw_XzpWjaVdh-J0JAz33WVzgsQGUc

{}
#######
PATCH http://localhost:3000/api/emergency-service-request/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3Mzk2ODkwLCJleHAiOjE3Nzc0ODMyOTB9.yYDcNkGg5f9W7MNIV7WPparZXZnsENbuV86l4C8Qszo

{ 
    "status": "COMPLETED",
    "completionTime": "2026-04-28T17:47:15.747Z"
    
}
#######
DELETE http://localhost:3000/api/emergency-service-request/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc3Mzk2ODkwLCJleHAiOjE3Nzc0ODMyOTB9.yYDcNkGg5f9W7MNIV7WPparZXZnsENbuV86l4C8Qszo

{ 

}