# ================================================================
# POST
# ================================================================


POST http://localhost:3000/api/medical-information/6
Content-Type: application/json
Authorization: Bearer ADMIN_TOKEN

{
    "conditions":  ["diabetes", "hypertension"],
    "medications": ["metformin", "lisinopril"],
    "avgHeartRate" : 120,
    "avgTemp" : 37,
    "avgSpo2" : 55
}



# ================================================================
# Get
# ================================================================


### Get All Medical Records
GET http://localhost:3000/api/drivers/medical-records
Content-Type: application/json
Authorization: Bearer ADMIN_TOKEN

###

### Get Medical Record By Driver Id
GET http://localhost:3000/api/medical-information/6
Content-Type: application/json
Authorization: Bearer ADMIN_TOKEN

###

GET http://localhost:3000/api/medical-information/custom-thresholds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzgyMTMwODg0LCJleHAiOjE3ODIyMTcyODR9.355vS6-CoH-xVeKGYwMEgHGsZUY0Y7Upcb3Mix11q-Q

###

# ================================================================
# UPDATE
# ================================================================


### Update Medical Record 
PATCH http://localhost:3000/api/medical-information/6
Content-Type: application/json
Authorization: Bearer ADMIN_TOKEN

{
    "conditions": ["astigmatism"],
    "avgHeartRate" : 110,
    "avgTemp" : 37,
    "avgSpo2" : 60
}


PATCH http://localhost:3000/api/medical-information/6
Content-Type: application/json
Authorization: Bearer ADMIN_TOKEN

{
    "conditions": ["astigmatism"]
}
