GET http://localhost:3000/api/reports/drivers/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3Nzc4MDgyMzYsImV4cCI6MTc3Nzg5NDYzNn0.ei8YkKZA8e0EzxzUBFV-NGPZdTpqsFbMjWJUDh4U6Hk

{}

#######
GET http://localhost:3000/api/reports/alerts/per-area?from=2026-05-02T20:30:00.000Z&to=2026-05-03T19:38:39.778Z
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzgyNjc5NTEsImV4cCI6MTc3ODM1NDM1MX0.LCNp1nwuR7OyCTfQMOgVTZ6H0pKy291cM9T5KpSXjQ0

{}
#########
GET http://localhost:3000/api/reports/emergency-performance?from=2026-05-01&to=2026-05-04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODE4MDY3MjMsImV4cCI6MTc4MTg5MzEyM30.jqCal7ksbPPXopzTKu9Xmt7IY3UNDeTLEA9F8VQWla8

{

}
###
GET http://localhost:3000/api/reports/alerts/yearly?fromYear=2026&toYear=2026
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3ODA5NDI5MywiZXhwIjoxNzc4MTgwNjkzfQ.zzAts9TtY8OOzBvb71mdX63LTA8D0N99uYzarblk9To

{

}
### 
GET http://localhost:3000/api/reports/fleet-managers/trips?from=1969-01-01&to=2025-08
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3ODA5NDI5MywiZXhwIjoxNzc4MTgwNjkzfQ.zzAts9TtY8OOzBvb71mdX63LTA8D0N99uYzarblk9To

{

}
