GET http://localhost:3000/api/reports/drivers/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODE4OTU0NDksImV4cCI6MTc4MTk4MTg0OX0.Ot2pKXi0KbzTH5D2jrnf6o0S4914egQzwWOO2l54pfA

{}



#######
GET http://localhost:3000/api/reports/alerts/per-area?from=2026-05-02T20:30:00.000Z&to=2026-05-03T19:38:39.778Z
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODE4OTU0NDksImV4cCI6MTc4MTk4MTg0OX0.Ot2pKXi0KbzTH5D2jrnf6o0S4914egQzwWOO2l54pfA


#########
GET http://localhost:3000/api/reports/emergency-performance?from=2026-05-01&to=2026-05-04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3ODA5NDI5MywiZXhwIjoxNzc4MTgwNjkzfQ.zzAts9TtY8OOzBvb71mdX63LTA8D0N99uYzarblk9To

{

}
###
GET http://localhost:3000/api/reports/alerts/yearly?fromYear=2026&toYear=2026
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3ODA5NDI5MywiZXhwIjoxNzc4MTgwNjkzfQ.zzAts9TtY8OOzBvb71mdX63LTA8D0N99uYzarblk9To

{

}
### 
GET http://localhost:3000/api/reports/fleet-managers/trips?from=1969-01-01&to=2025-08
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3ODA5NDI5MywiZXhwIjoxNzc4MTgwNjkzfQ.zzAts9TtY8OOzBvb71mdX63LTA8D0N99uYzarblk9To

{

}
