POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{ 
    "email":"fleetManager@gmail.com",
    "fName":"Fleet",
    "lName":"Manager",
    "password":"Fleet@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"FLEET_MANAGER" 
} 

######
POST http://localhost:3000/api/auth/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc2OTM5MzA1LCJleHAiOjE3NzcwMjU3MDV9.oxilPdvDpx3k9GJK_ix64Be3td2659pEek_yRLsLd_o

{ 
    "email":"driver@gmail.com",
    "fName":"Driver",
    "lName":"Driver",
    "password":"Driver@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"DRIVER" ,
    "drivingLicense":"abc123456"
} 

######
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{ 
    "email":"driver6@gmail.com",
    "fName":"Driver",
    "lName":"Driver",
    "password":"Driver6@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"DRIVER" ,
    "drivingLicense":"abc123456"
} 

#####

######
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{ 
    "email":"driver7@gmail.com",
    "fName":"Driver",
    "lName":"Driver",
    "password":"Driver7@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"DRIVER" ,
    "drivingLicense":"abc123456"
} 

#####

POST http://localhost:3000/api/users
Content-Type: application/json

{ 
    "email":"admin@gmail.com",
    "fName":"AdminfName",
    "lName":"AdminlName",
    "password":"Admin@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"ADMIN" 
} 
########
POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzgyNjc5NTEsImV4cCI6MTc3ODM1NDM1MX0.LCNp1nwuR7OyCTfQMOgVTZ6H0pKy291cM9T5KpSXjQ0

{ 
    "email":"driver@gmail.com",
    "fName":"Dri",
    "lName":"ver",
    "password":"Driver@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"DRIVER" 
} 