POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{ 
    "email":"fleetManager@gmail.com",
    "fName":"Fleet",
    "lName":"Manager",
    "password":"Fleet@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"FLEET_MANAGER" 
} 

######
POST http://localhost:3000/api/auth/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc2OTM5MzA1LCJleHAiOjE3NzcwMjU3MDV9.oxilPdvDpx3k9GJK_ix64Be3td2659pEek_yRLsLd_o

{ 
    "email":"driver5@gmail.com",
    "fName":"Driver",
    "lName":"Driver",
    "password":"Driver@12345678",
    "phone":["01122226666"],
    "address":"abcd",
    "role":"DRIVER" ,
    "drivingLicense":"abc123456"
} 