GET http://localhost:3000/api/trips/7/gps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJGTEVFVF9NQU5BR0VSIiwiaWF0IjoxNzc2ODE2MzI3LCJleHAiOjE3NzY5MDI3Mjd9.qrtnLL23jHZG6YXTluzms1Hb-4iNfPpzjOByASmcqVA