GET http://localhost:3000/api/trips/23/gps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzczODA3NTcsImV4cCI6MTc3NzQ2NzE1N30.e-ezM_3QqaLQQ55BI5Yikv_UTZWsowN-eS6zHMim8Ro

### 
POST http://localhost:3000/api/trips/67/gps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNzgyNjcwNTk4LCJleHAiOjE3ODI3NTY5OTh9.FP3bEz8VStPBYoudeq1HUlILKhpMtv7Kd-3aQw7UZPo

{
    "latitude" : 2.1125,
    "longitude": 30.5121
}
#######
POST http://localhost:3000/api/trips/1/gps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NzczOTc0NjgsImV4cCI6MTc3NzQ4Mzg2OH0.b2rl87tt81T0xH7eujxlwavaPLNZEQszjRTsd9Lnw0o

{
    "latitude" : 2.1125,
    "longitude": 2.1121
}
