POST http://localhost:3000/api/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NjcxMTI1NSwiZXhwIjoxNzc2Nzk3NjU1fQ.BoC0b0G5_EPnwId83_HTIxQEsNnP4lLO1c7Kk3wm-Fc

{ 
    "startPoint":"Alexandria",
    "destPoint":"Cairo",
    "startTime": "2026-04-20T20:30"

} 

#########
POST http://localhost:3000/api/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    "startPoint":"Alexandria",
    "destPoint":"China",
    "plannedStartTime": "2026-04-20T20:30:00.000Z",
    "driverId": 6,
    "fleetManagerId": 3
} 

########get all trips admin or fleet manager
GET http://localhost:3000/api/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    
} 
########get all trips admin or fleet manager
GET http://localhost:3000/api/trips?fromStartDate=2026-04-20T20:30:00.000Z&status=PLANNED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    
} 
#######get trips for a specific driver
GET http://localhost:3000/api/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NzY5NDUxNjEsImV4cCI6MTc3NzAzMTU2MX0.a8z_k20MhnAszMAgLUcaZebGjddbGM19CEIGicm247o

{ 
    
} 
########specific admin or fleet manager
GET http://localhost:3000/api/trips/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    
}
#######get a specific trip for a specific driver
GET http://localhost:3000/api/trips/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NzY5NDUxNjEsImV4cCI6MTc3NzAzMTU2MX0.a8z_k20MhnAszMAgLUcaZebGjddbGM19CEIGicm247o

{ 
    
} 
#######delete trip unauthorized
DELETE http://localhost:3000/api/trips/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NzY3ODU2MDksImV4cCI6MTc3Njg3MjAwOX0.WPU3CFgIxJbFZ5Q6bZ0ej8u13yKRz1t1aD5fOPNFZws

{ 
    
} 
########DELETE TRIP fleet manager
DELETE  http://localhost:3000/api/trips/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    
}

######### patch as driver
PATCH  http://localhost:3000/api/trips/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJyb2xlIjoiRkxFRVRfTUFOQUdFUiIsImlhdCI6MTc3NzE5OTM2OCwiZXhwIjoxNzc3Mjg1NzY4fQ.flF57hsD178fNTGXgffvtzw9jERyPKjm-Z48Kmax9kc

{ 
    "endTime": "2026-04-20T20:30:00.000Z",
    "status": "ONGOING"
} 