GET http://localhost:3000/api/wearablebands/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NzczOTY3MDIsImV4cCI6MTc3NzQ4MzEwMn0.-4i9HKXpJRbWHXaw5htdbg6hBWy8Es3F53_I8pjf_6c