GET http://localhost:3000/api/wearablebands/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODE4MDY3MjMsImV4cCI6MTc4MTg5MzEyM30.jqCal7ksbPPXopzTKu9Xmt7IY3UNDeTLEA9F8VQWla8


######

POST http://localhost:3000/api/wearablebands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Nzg0MDIxOSwiZXhwIjoxNzc3OTI2NjE5fQ.tKPu9UHgVJcO9H6NK5k3sG-lwOOzlFIhGXGK67ZeC1c

{
    "deviceId": 2,
    "sensorList": ["gps"]

}

######
DELETE http://localhost:3000/api/wearablebands/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Nzg0MDIxOSwiZXhwIjoxNzc3OTI2NjE5fQ.tKPu9UHgVJcO9H6NK5k3sG-lwOOzlFIhGXGK67ZeC1c

{
   

}

#####
PATCH http://localhost:3000/api/wearablebands/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3Nzg0MDIxOSwiZXhwIjoxNzc3OTI2NjE5fQ.tKPu9UHgVJcO9H6NK5k3sG-lwOOzlFIhGXGK67ZeC1c

{
   "sensorList" : ["sensor1", "Sensor2"], 
   "driverId" : 2,
   "isConnected": true

}
