GET http://localhost:3000/api/wearablebands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NzU4Njg5MCwiZXhwIjoxNzc3NjczMjkwfQ.i9XioDg6ipZEdOTCYvvba9j7QAXCqqSeCAwO-olYN7I

{

}

######

POST http://localhost:3000/api/wearablebands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NzU4Njg5MCwiZXhwIjoxNzc3NjczMjkwfQ.i9XioDg6ipZEdOTCYvvba9j7QAXCqqSeCAwO-olYN7I

{
    "sensorList": ["gps"],
    "driverId": 13
    
}